NebengDong/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/auth/", include("authentication.urls")),
    path('profile/', include('user_profile.urls')),
    path('history/', include('history.urls')),
    path('report/', include('report_pengguna.urls')),
    path('buka-tumpangan/', include('buka_tumpangan.urls')),
    path('cari-tumpangan/', include('cari_tumpangan.urls')),
    path('report-list/', include('report_list.urls')),
    path('', include("home.urls"))
]

authentication/urls.py
from django.urls import path
from .views import *

app_name = 'authentication'

urlpatterns = [
    path('login/', login_pengguna.as_view(), name='login_pengguna'),
    path('logout/', logout_user.as_view(), name='logout'),
    path('login_tim/', login_tim, name='login_tim'),
    path('home/', home, name='home'),
    path('create_superuser/', create_superuser_view, name='create_superuser'),
]

buka_tumpangan/urls.py
from django.urls import path
from .views import *

app_name = 'buka_tumpangan'

urlpatterns = [
    path('new/', buka_tumpangan, name='buka_tumpangan'),
    path('detail/<str:id>', show_detail_tumpangan, name='show_detail_tumpangan'),
    path('update/<str:pengajuan_id>/<str:status>/', update_pengajuan, name='update_pengajuan'),
    path('delete/<str:tumpangan_id>', delete_tumpangan, name='delete_tumpangan'),
    path('confirm_tumpangan/<str:tumpangan_id>/', confirm_tumpangan, name='confirm_tumpangan'),
    path('close-offer/<str:tumpangan_id>/', close_offer, name='close_offer'),
    path('get-pengajuan/<str:tumpangan_id>/', get_pengajuan, name='get-pengajuan'),
    path('check-no-kendaraan/', check_no_kendaraan, name='check_no_kendaraan'),
]

cari_tumpangan/urls.py
from django.urls import path
from cari_tumpangan.views import *

app_name = 'cari_tumpangan'

urlpatterns = [
    path('', all_tumpangan, name='all_tumpangan'),
    path('detail/<uuid:tumpangan_id>', tumpangan_detail, name='tumpangan_detail'),
    path('book/', apply_tumpangan, name='apply_tumpangan'),
]

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', index, name='home'),
]

report_list/urls.py
from django.urls import path
from report_list.views import show_report_list
from report_list.views import show_report_list_by_id

app_name = 'report_list'

urlpatterns = [
    path('', show_report_list, name='show_report_list'),
    path('<uuid:id>', show_report_list_by_id, name='show_report_list_by_id'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from nebengdongapp.models import *
from nebengdongapp.models.enum_model import *

def index(request):
    if request.user.is_authenticated and request.user.is_superuser == False:
        pengguna = Pengguna.objects.get(user_id=request.user.id)
        no_kendaraan = pengguna.no_kendaraan
        notifs = NotifikasiPengajuanTumpangan.objects.filter(user=pengguna).order_by('-timestamp')[:5]
        tumpangan_list = Tumpangan.objects.filter(status=StatusTumpangan.BUKA).exclude(pembuka_tumpangan=pengguna)[:5]
        pengajuan_tumpangan_dict = {}
        for tumpangan in tumpangan_list:
            pengajuan_tumpangan_dict[tumpangan.id] = PengajuanTumpangan.objects.filter(tumpangan=tumpangan, pencari_tumpangan=pengguna).exists()
    else:
        pengguna = None
        no_kendaraan = ''
        notifs = []
        tumpangan_list = []
        pengajuan_tumpangan_dict = {}
    
    context = {
        'pengguna': pengguna,
        'notifs': notifs,
        'tumpangan_list': tumpangan_list,
        'pengajuan_tumpangan_dict': pengajuan_tumpangan_dict,
        'no_kendaraan': no_kendaraan
    }

    return render(request, 'index.html', context)

home/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>NebengDong</title>
<style>
    .btn {
        border-radius: 12px;
    }

    .card {
        border-radius: 12px;
    }

    .typing-animation {
        font-family: 'Poppins';
        font-size: 24px;
        white-space: prewrap;
        overflow: hidden;
    }

    .typing-animation h2 {
        display: inline-block;
        overflow: hidden;
        white-space: nowrap;
        animation: typing 2s steps(14, end) forwards, blink-caret 0.75s step-end infinite;
    }

    @keyframes typing {
        from { width: 0; }
        to { width: 100%; }
    }

    @keyframes blink-caret {
        from, to { border-right: 2px solid transparent; }
        50% { border-right: 2px solid #333; }
    }
    
    @media (max-width: 768px) {
        .typing-animation h2{
            white-space: pre-wrap;
            font-size: 20px; /* Adjust font size for smaller screens */
        }
    }

</style>
{% endblock meta %}
{% block content %}

{% if user.is_authenticated and not user.is_superuser %}
    <div class="dropdown text-right mt-5 mr-3">
        <button class="btn btn-outline-secondary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Notification
        </button>
        {% if notifs %}
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for notif in notifs %}
                {% if forloop.counter0 == 0 %}
                    <a class="dropdown-item" href="#">Tujuan {{ notif.pengajuan_tumpangan.tumpangan.lokasi_tujuan }} &rarr; {{ notif.pengajuan_tumpangan.status_pengajuan }}</a>
                {% else %}
                    <a class="dropdown-item disabled" href="#">Tujuan {{ notif.pengajuan_tumpangan.tumpangan.lokasi_tujuan }} &rarr; {{ notif.pengajuan_tumpangan.status_pengajuan }}</a>
                {% endif %}
                {% endfor %}
            </div>
        {% else %}
            <div class="dropdown-menu p-4 text-muted">
                <p>Empty</p>
            </div>
        {% endif %}
    </div>
{% endif %}

<div class="container my-5">
    <div class="text-center w-75 mx-auto mb-5">
        <img class="w-100 h-auto mb-3" src="{% static 'image/home_img.png' %}"/>
        <div class="typing-animation mb-3">
            <h2>Find new friends and transport with ease.</h2>
        </div>
        <center>
        {% if not user.is_authenticated %}
            <button type="button" class="button btn text-light" style="background-color: #120DFA; font-weight: bold;" onclick="window.location.href='{% url 'authentication:home' %}'">Join NebengDong Now!</button>
        {% elif user.is_authenticated and user.is_superuser %}
            <button type="button" class="button btn text-light" style="background-color: #120DFA; font-weight: bold;" onclick="window.location.href='{% url 'report_list:show_report_list' %}'">Lihat Laporan</button>
        {% elif user.is_authenticated and not user.is_superuser and tumpangan_list %}
            <button type="button" class="button btn text-light" style="background-color: #120DFA; font-weight: bold;" onclick="window.location.href='{% url 'buka_tumpangan:buka_tumpangan' %}'">Buka Tumpangan</button>
        {% elif user.is_authenticated and not user.is_superuser and not tumpangan_list %}
            <button type="button" class="button btn text-light mb-2" style="background-color: #120DFA; font-weight: bold; border-top-left-radius: 12px; border-bottom-left-radius: 12px;" onclick="window.location.href='{% url 'buka_tumpangan:buka_tumpangan' %}'">Buka Tumpangan</button>
            <button type="button" class="button btn text-light mb-2" style="background-color: #120DFA; font-weight: bold; border-top-right-radius: 12px; border-bottom-right-radius: 12px;" onclick="window.location.href='{% url 'cari_tumpangan:all_tumpangan' %}'">Cari Tumpangan</button>
        {% endif %}
        </center>
    </div>

    {% if user.is_authenticated and not user.is_superuser and tumpangan_list %}
        <div class="mx-auto mb-5">
            <div class="row mb-2">
                <div class="col-sm-8">
                    <h4 style="font-weight: bold;">Cari Tumpangan</h4>
                </div>
                <div class="col-sm-4 text-right">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-sm text-light" style="background-color: #120DFA; font-weight: 500; border-top-left-radius: 12px; border-bottom-left-radius: 12px;" href="#carouselControls" data-slide="prev">Prev</button>
                        <button type="button" class="btn btn-sm text-light" style="background-color: #120DFA; font-weight: 500;" href="#carouselControls" data-slide="next">Next</button>
                        <button type="button" class="btn btn-sm text-light" style="background-color: #120DFA; font-weight: 500; border-top-right-radius: 12px; border-bottom-right-radius: 12px;" onclick="window.location.href='{% url 'cari_tumpangan:all_tumpangan' %}'">See all</button>
                    </div>
                </div>
            </div>
            <div id="carouselControls" class="carousel slide overflow-auto" data-ride="carousel">
                <div class="carousel-inner">
                    {% for tumpangan in tumpangan_list %}
                    {% if forloop.counter0 == 0 %}
                    <div class="carousel-item active">
                    {% else %}
                    <div class="carousel-item">
                    {% endif %}
                        <div class="card slider-card border-primary shadow-sm mx-auto">
                            <div class="card-body">
                                <div class="row mb-3">
                                    <div class="col-lg-8">
                                        <h5 class="card-title">{{tumpangan.lokasi_asal}} to {{tumpangan.lokasi_tujuan}}</h5>
                                    </div>
                                    <div class="col-lg-4">
                                        <h5 class="card-title">&#128100; {{tumpangan.pembuka_tumpangan.nama}}</h5>
                                    </div>
                                </div>
                                <div class="row t-detail mb-2">
                                    <div class="col-sm-3 col-lg">&#128186; {{tumpangan.kapasitas}} Seats</div>
                                    <div class="col-sm col-lg">&#128181; Rp{{tumpangan.tarif}}</div>
                                    <div class="col-sm-5 col-lg">&#128338; {{tumpangan.depart}}</div>
                                </div>
                                <a href="/cari-tumpangan/detail/{{tumpangan.id}}" class="stretched-link"></a>
                            </div>
            
                            <div class="card-footer text-right" style="z-index: 3; background-color: transparent; border: none;">
                                <form method="POST" class="pb-2" action="{% url 'cari_tumpangan:apply_tumpangan' %}" onsubmit="return validateForm('{{ tumpangan.id }}');">
                                    {% csrf_token %}
                                    <input type="hidden" name="tumpangan_id" value="{{ tumpangan.id }}">
                                    <div class="btn-group">
                                        {% if pengajuan_tumpangan_dict|get_item:tumpangan.id %}
                                            <button type="submit" class="btn" style="background-color: #FFCA0D; border-top-left-radius: 12px; border-bottom-left-radius: 12px;" disabled>Booked</button>
                                        {% else %}
                                            <button type="submit" class="btn" style="background-color: #FFCA0D; border-top-left-radius: 12px; border-bottom-left-radius: 12px;">Book</button>
                                        {% endif %}
                                        <button type="button" class="btn dropdown-toggle dropdown-toggle-split" style="background-color: #FFCA0D; border-top-right-radius: 12px; border-bottom-right-radius: 12px;" data-toggle="dropdown">
                                            <span>&#128490;</span>
                                        </button>
                                        <ul class="dropdown-menu">
                                            {% if tumpangan.pembuka_tumpangan.no_wa %}
                                                <li><a class="dropdown-item" href="https://wa.me/{{tumpangan.pembuka_tumpangan.no_wa}}" target="_blank" rel="noopener noreferrer">WhatsApp</a></li>
                                            {% endif %}
                                            {% if tumpangan.pembuka_tumpangan.id_line %}
                                                <li><a class="dropdown-item" href="https://line.me/ti/p/~{{tumpangan.pembuka_tumpangan.id_line}}" target="_blank" rel="noopener noreferrer">LINE</a></li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
</div>
<script>
    var userBooked = '{{pengguna.is_on_tumpangan}}'
    var userWaExist = '{{pengguna.no_wa}}'
    var userLineExist = '{{pengguna.id_line}}'
    function validateForm(tumpanganId) {
        if (userBooked == "False") {
            if (userWaExist != "" || userLineExist != "") {
                return true;
            }
            showAlert('FAILED', 'Kamu belum mengisi informasi kontak. Isi terlebih dahulu', 
                    'Back', '', '', '')
            return false;
        } else {
            showAlert('FAILED', 'Kamu masih berada dalam tumpangan. Selesaikan terlebih dahulu', 
                    'Back', '', '', '')
            return false;
        }
    }
</script>
{% endblock content %}  