NebengDong/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/auth/", include("authentication.urls")),
    path('profile/', include('user_profile.urls')),
    path('history/', include('history.urls')),
    path('report/', include('report_pengguna.urls')),
    path('buka-tumpangan/', include('buka_tumpangan.urls')),
    path('cari-tumpangan/', include('cari_tumpangan.urls')),
    path('report-list/', include('report_list.urls')),
    path('', include("home.urls"))
]

buka_tumpangan/urls.py
from django.urls import path
from .views import *

app_name = 'buka_tumpangan'

urlpatterns = [
    path('new/', buka_tumpangan, name='buka_tumpangan'),
    path('detail/<str:id>', show_detail_tumpangan, name='show_detail_tumpangan'),
    path('update/<str:pengajuan_id>/<str:status>/', update_pengajuan, name='update_pengajuan'),
    path('delete/<str:tumpangan_id>', delete_tumpangan, name='delete_tumpangan'),
    path('confirm_tumpangan/<str:tumpangan_id>/', confirm_tumpangan, name='confirm_tumpangan'),
    path('close-offer/<str:tumpangan_id>/', close_offer, name='close_offer'),
    path('get-pengajuan/<str:tumpangan_id>/', get_pengajuan, name='get-pengajuan'),
    path('check-no-kendaraan/', check_no_kendaraan, name='check_no_kendaraan'),
]

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', index, name='home'),
]

buka_tumpangan/models.py
from django.db import models

# Create your models here.

buka_tumpangan/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, JsonResponse
from nebengdongapp.models import *
from nebengdongapp.models.enum_model import *
import uuid
from django.views.decorators.csrf import csrf_exempt

# Create new tumpangan
@login_required(login_url='authentication:login')
def buka_tumpangan(request):
    pembuka_tumpangan = Pengguna.objects.get(user=request.user)
    if request.method == 'POST':
        lokasi_asal = request.POST.get("lokasi_asal")
        lokasi_tujuan = request.POST.get("lokasi_tujuan")
        depart = request.POST.get("depart")
        kapasitas = request.POST.get("kapasitas")
        tarif = request.POST.get("tarif")
        deskripsi = request.POST.get("deskripsi")

        tumpangan = Tumpangan(
                            id= uuid.uuid4(),
                            lokasi_asal=lokasi_asal,
                            lokasi_tujuan=lokasi_tujuan,
                            depart=depart,
                            kapasitas=kapasitas,
                            tarif=tarif,
                            status='OP',
                            deskripsi=deskripsi,
                            pembuka_tumpangan=pembuka_tumpangan
                        )
        tumpangan.save()

        return JsonResponse({
              "message": "Successfully Add New Tumpangan",
              "pk": tumpangan.id, 
                "fields": {
                    "lokasi_asal":lokasi_asal,
                    "lokasi_tujuan":lokasi_tujuan,
                    "depart":depart,
                    "kapasitas":kapasitas,
                    "tarif":tarif,
                    "status":'OP',
                    "deskripsi":deskripsi
                    }
            }, status=200)
        
    context = {
        "lokasi_choices": [{
            'value': choice[1],
            'label': choice[0]
        } for choice in LokasiDiUI.choices],
        'is_on_tumpangan': pembuka_tumpangan.is_on_tumpangan
    }
    return render(request, "buka_tumpangan.html", context)

# Update tumpangan
@login_required(login_url='authentication:login')
def update_pengajuan(request, pengajuan_id, status):
    pengajuan = PengajuanTumpangan.objects.filter(pk=pengajuan_id).first()
    pengajuan.status_pengajuan = status
    pengajuan.save()

    notifikasi = NotifikasiPengajuanTumpangan(
        id=uuid.uuid4(),
        user=pengajuan.pencari_tumpangan,
        pengajuan_tumpangan=pengajuan
    )
    notifikasi.save()

    return JsonResponse(
            {
                "message": f"Berhasil memperbarui status pengajuan {pengajuan_id} menjadi {status}",
            }, 
            status=200)
    
# konfirmasi tumpangan
@csrf_exempt
@login_required(login_url='authentication:login')
def confirm_tumpangan(request, tumpangan_id):
    user = request.user
    tumpangan = Tumpangan.objects.get(pk=tumpangan_id)
    pembuka_tumpangan = tumpangan.pembuka_tumpangan
    
    # jika pembuka tumpangan
    if pembuka_tumpangan.user_id == user.id:
        # update status tumpangan
        tumpangan.status = StatusTumpangan.SELESAI
        pembuka = Pengguna.objects.get(pk=pembuka_tumpangan.id)
        pembuka.is_on_tumpangan = False
        tumpangan.save()
        pembuka.save()
        
    # jika penumpang
    else:
        # get penumpang and pengajuan
        penumpang = Pengguna.objects.get(user_id = user.id)
        pengajuan = PengajuanTumpangan.objects.get(pencari_tumpangan=penumpang, tumpangan=tumpangan)
        
        # update status pengajuan
        pengajuan.status_pengajuan = StatusPengajuanTumpangan.SELESAI
        penumpang.is_on_tumpangan = False
        pengajuan.save()
        penumpang.save()

    return JsonResponse(
            {
                "message": f"Selamat! Anda telah sampai tujuan, terima kasih telah menggunakan nebengDong!"
            }, 
            status=200)



# konfirmasi tumpangan
@login_required(login_url='authentication:login')
def close_offer(request, tumpangan_id):
    tumpangan = Tumpangan.objects.get(pk=tumpangan_id)
    pengguna_id = Pengguna.objects.get(user_id=request.user.id)
    if pengguna_id == tumpangan.pembuka_tumpangan:
        tumpangan.status = StatusTumpangan.OTW
        tumpangan.save()

        pembuka_tumpangan = tumpangan.pembuka_tumpangan
        pembuka_tumpangan.is_on_tumpangan = True
        pembuka_tumpangan.save()

        pengajuan_diterima = []
        pengajuan_ditolak = []
        pengajuan_acc = PengajuanTumpangan.objects.filter(tumpangan_id=tumpangan_id)
        for pengajuan in pengajuan_acc:
            penumpang = Pengguna.objects.get(id=pengajuan.pencari_tumpangan.id)
            if pengajuan.status_pengajuan == 'DITERIMA':
                penumpang.is_on_tumpangan = True
                pengajuan_diterima.append(pengajuan.id)
                penumpang.save()
            elif pengajuan.status_pengajuan == 'MENGAJUKAN' or pengajuan.status_pengajuan == 'Mengajukan':
                pengajuan.status_pengajuan = 'DITOLAK'
                pengajuan.save()
                pengajuan_ditolak.append(pengajuan.id)

        return JsonResponse(
                {
                    "message": "Successfully Close Offer",
                    "pengajuan_ditolak": pengajuan_ditolak,
                    "pengajuan_diterima": pengajuan_diterima
                }, 
                status=200)
    else:
        return JsonResponse({"error": "You do not have permission to access this resource."}, status=403)        

# Delete tumpangan
@login_required(login_url='authentication:login')
def delete_tumpangan(request, tumpangan_id):
    tumpangan = Tumpangan.objects.filter(pk=tumpangan_id).first()
    pengguna_id = Pengguna.objects.get(user_id=request.user.id)
    if pengguna_id == tumpangan.pembuka_tumpangan:
        tumpangan.delete()
        return JsonResponse(
                {
                    "message": "Successfully Delete Tumpangan"
                }, 
                status=200)
    else:
        return JsonResponse({"error": "You do not have permission to access this resource."}, status=403)
    
@login_required(login_url='authentication:login')
def check_no_kendaraan(request):
    pengguna = Pengguna.objects.get(user_id=request.user.id)
    if pengguna.no_wa == '' and pengguna.id_line == '':
        return JsonResponse({
                                "message": "Kamu belum mengisi informasi kontak. Lengkapi dulu yuk"
                            }, status=200)
    elif pengguna.no_kendaraan == '':
        return JsonResponse(
                {
                    "message": "Kamu belum mengisi nomor kendaraan. Lengkapi dulu yuk"
                }, 
                status=200)
    else:
        return JsonResponse({
                                "message": "success"
                            }, status=200)


@login_required(login_url='authentication:login')
def show_detail_tumpangan(request, id):
    tumpangan = Tumpangan.objects.get(id=id)
    pengguna_id = Pengguna.objects.get(user_id=request.user.id)

    if pengguna_id == tumpangan.pembuka_tumpangan:
        context = {
            'id': tumpangan.id,
            'lokasi_asal': tumpangan.lokasi_asal,
            'lokasi_tujuan': tumpangan.lokasi_tujuan,
            'depart': tumpangan.depart,
            'kapasitas': tumpangan.kapasitas,
            'tarif': tumpangan.tarif,
            'deskripsi': tumpangan.deskripsi,
            'status': tumpangan.get_status_tumpangan(),
        }
        return render(request, "manage_tumpangan.html", context)
    else:
        return JsonResponse({"error": "You do not have permission to access this resource."}, status=403)
    
@login_required(login_url='authentication:login')
def get_pengajuan(request, tumpangan_id):
    tumpangan = Tumpangan.objects.get(id=tumpangan_id)
    pengguna_id = Pengguna.objects.get(user_id=request.user.id)

    if pengguna_id == tumpangan.pembuka_tumpangan:
        pengajuan_list = PengajuanTumpangan.objects.filter(tumpangan=tumpangan)
        pengajuan_diterima = pengajuan_list.filter(status_pengajuan='DITERIMA')
        
        data = []
        for pengajuan in pengajuan_list:
            pengguna = Pengguna.objects.get(id=pengajuan.pencari_tumpangan.id)
            data.append({
                "pengajuan": pengajuan.serialize(),
                "pengguna": pengguna.serialize()
            })
        response = {
            'jml_diterima': len(pengajuan_diterima),
            'data': data
        }
        return JsonResponse(response, safe=False)
    else:
        return JsonResponse({"error": "You do not have permission to access this resource."}, status=403)

buka_tumpangan/templates/buka_tumpangan.html
{% extends 'base.html' %}
{% load static %}

 {% block meta %}
  <title>Buka Tumpangan</title>
  <style>
    .form-group {
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      gap: 9px;
    }

    .select {
      display: flex;
      align-items: center;
      gap: 10px;
    }

    label {
      color: #000;
      font-size: 16px;
      font-style: normal;
      font-weight: 700;
      line-height: normal;
    }

  </style>
 {% endblock meta %}

 {% block content %}
 <div class="container mt-5">
    <h2><b><span class="title yellow">Buka</span> <span class="title blue">Tumpangan</span></b></h2>
    <form id="add-tumpangan" class="flex flex-start gap-4" novalidate>
      {% csrf_token %}
      <div class="row w-100 rows-cols-1 row-cols-md-3 mt-3">
        <div class="col-md-4">
          <div class="form-group p-2">
            <label class="fw-semibold" for="lokasiAsal">Lokasi Asal*</label>
            <select required class="form-control " id="lokasi_asal" name="lokasi_asal">
                <option disabled selected>Pilih lokasi asal</option>
                {% for choice in lokasi_choices %}
                <option value="{{ choice.label }}">{{ choice.label }}</option>
                {% endfor %}
            </select>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group p-2">
            <label class="fw-semibold" for="lokasiTujuan">Lokasi Tujuan*</label>
            <select required class="form-control " id="lokasi_tujuan" name="lokasi_tujuan">
                <option disabled selected>Pilih lokasi tujuan</option>
                {% for choice in lokasi_choices %}
                <option value="{{ choice.label }}">{{ choice.label }}</option>
                {% endfor %}
            </select>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group p-2">
            <label class="fw-semibold" for="tarif">Tarif per Orang*</label>
            <input required type="number" class="form-control " id="tarif" name="tarif" placeholder="Isi Tarif">
          </div>
        </div>
      </div>
      <div class="row w-100 mt-3">
        <div class="col-md-4">
          <div class="form-group p-2">
            <label class="fw-semibold" for="deskripsi">Deskripsi</label>
            <textarea class="form-control " id="deskripsi" name="deskripsi" rows="3" placeholder="Tuliskan informasi tambahan di sini"></textarea>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group p-2">
            <label class="fw-semibold" for="kapasitas">Kapasitas Penumpang*</label>
            <input required type="number" class="form-control " id="kapasitas" name="kapasitas" placeholder="Isi Kapasitas">
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group p-2">
            <label class="fw-semibold" for="depart">Waktu Keberangkatan*</label>
            <input required type="datetime-local" class="form-control " id="depart" name="depart" placeholder="Isi Waktu Keberangkatan">
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-center gap-2 my-5">
        <div class="m-2">
          <button type="button" class="button py-3" onclick="bukaTumpangan()">Buka Tumpangan</button>
        </div>
        <div class="m-2">
          <button type="button" class="button-outline py-3" onclick="window.location.href='/'">Kembali ke Home</button>
        </div>
      </div>
    </form>
  </div>

  <script>
    var id = ""
  function validateForm() {
    return ($('#lokasi_asal').val() !== null)
          && ($('#lokasi_tujuan').val() !== null)
          && ($('#tarif').val() !== '')
          && ($('#kapasitas').val() !== '') 
          && ($('#depart').val() !== '')
  }

  var validUser = '{{is_on_tumpangan}}'
  var bukaTumpangan = function() {
    if (validateForm()) {
      if (validUser === 'True') {
        showAlert('FAILED', 'Kamu sudah memulai tumpangan. Selesaikan terlebih dahulu', 
                    'Back', '', '', '')
        return;
      }
      var formData = $("#add-tumpangan").serialize();
      $.ajax({
          type: "POST",
          url: "/buka-tumpangan/new/",
          data: formData,
          dataType: "json",
          encode: true,
        }).done(function (data) {
          id = data.pk
          showAlert('SUCCESS', 'Berhasil membuka tumpangan', 
                  'See Details', seeDetails,
                  '', '')
          $("#add-tumpangan").trigger("reset");
        })
    } else {
      showAlert('FAILED', 'Mohon isi input dengan benar', 
                  'Back', '', '', '')
    }
  }

  function seeDetails() {
    window.location.href = `/buka-tumpangan/detail/${id}`;
  }

  </script>
  <script type="text/javascript" src="{% static 'js/buka_tumpangan.js' %}"></script>

 {% endblock content %}

buka_tumpangan/templates/manage_tumpangan.html
{% extends 'base.html' %}
{% load static %}

 {% block meta %}
  <title>Detail Tumpangan</title>
  <style>
    .icon {
      width: 24px;
      height: 24px;
    }

    .form-control::placeholder {
      color: #1E1E1E;
    }

    .form-control:read-only {
      background-color: white;
    }

    .fw-semibold {
      color: #000;
      font-size: 16px;
      font-style: normal;
      font-weight: 700;
      line-height: normal;
    }

    .subtitle {
      font-family: Newake;
      font-size: 30px;
      font-style: normal;
      font-weight: 400;
      line-height: normal;
    }

    .button-acc {
      display: flex;
      height: 40px;
      padding: 8px 32px;
      justify-content: center;
      align-items: center;
      gap: 10px;
      border-radius: 12px;
      border: 0;
      color: var(--neutral-50, #F6F6F6);
      font-size: 14px;
      font-style: normal;
      font-family: 'Poppins';
      font-weight: 700;
      line-height: normal;
      background: linear-gradient(182deg, #9B99F8 2.05%, #9A83F8 114.14%);  
      /* Drop Shadow */
      box-shadow: 0px 2px 4px 0px rgba(6, 6, 6, 0.20);
      border: 0;
    }

    .box {
      border-radius: 8px;
      border: 2px solid #ADADAD;
    }
  </style>
 {% endblock meta %}

 {% block content %}
 
 <div class="container my-5">
    <h2><b><span class="title yellow">Informasi</span> <span class="title blue">Tumpangan</span></b></h2>
    <form id="add-tumpangan" class="flex flex-start gap-4" novalidate>
      <div class="row w-100 rows-cols-1 row-cols-md-3 mt-3">
        <div class="col-md-4">
          <div class="form-group p-2">
            <label class="fw-semibold" for="lokasiAsal">Lokasi Asal</label>
            <input readonly type="number" class="background-white form-control"placeholder="{{lokasi_asal}}">
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group p-2">
            <label class="fw-semibold" for="lokasiTujuan">Lokasi Tujuan</label>
            <input readonly type="number" class="background-white form-control "placeholder="{{lokasi_tujuan}}">
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group p-2">
            <label class="fw-semibold" for="tarif">Tarif per Orang</label>
            <input readonly type="number" class="background-white form-control "placeholder="Rp {{tarif}}">
          </div>
        </div>
      </div>
      <div class="row w-100 mt-3">
        <div class="col-md-4">
          <div class="form-group p-2">
            <label class="fw-semibold" for="deskripsi">Deskripsi</label>
            <textarea readonly class="background-white form-control " id="deskripsi" name="deskripsi" rows="3" placeholder="{{deskripsi}}"></textarea>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group p-2">
            <label class="fw-semibold" for="kapasitas">Kapasitas Penumpang</label>
            <input readonly type="number" class="background-white form-control " id="kapasitas" name="kapasitas" placeholder="{{kapasitas}}">
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group p-2">
            <label class="fw-semibold" for="depart">Waktu Keberangkatan</label>
            <input readonly class="background-white form-control " id="depart" name="depart" placeholder="{{depart}}">
          </div>
        </div>
      </div>
      <div>
          <h4 class="subtitle blue mt-4">Kelola penumpangmu di sini</h4>
          <h5 class="text-nowrap fw-semibold mt-3" id="counter-penumpang"><b></b></h5>

          <!-- Display List of Penumpang with Checkboxes or Cross Buttons -->
          <div class="container">
            <div class="penumpang w-100 row rows-cols-1 row-cols-md-3 g-4 justify-content-center">
            </div>
          </div>
      </div>

    <div class="my-5">
      <!-- Safely Arrived Button -->
      <div id="buttonOT">
        {% if status == "OT" %}
        <div class="d-flex justify-content-center gap-2">
          <div class="m-2">
            <form method="post" id="confirmForm">
              <input type="hidden" id="tumpanganId" value="{{id}}">
              {% csrf_token %}
              <button type="button" class="m-2 button mr-2 py-3" id="confirmButton" onclick="endTumpangan()">Tumpangan Selesai</button>
            </form>
          </div>
          <div class="m-2">
            <!-- Panic Button -->
            <a type="button" href="tel:+6281291203330" class="m-2 button-outline mr-2 py-3" id="panicButton">
              <img class="icon" src="{% static 'image/panic.png' %}" />Panic Button
            </a>
          </div>
        </div>
        {% endif %}
      </div>
      <div id="buttonOP">
        {% if status == "OP" %}
          {% csrf_token %}
          <div class="d-flex justify-content-center gap-2">
            <div class="m-2">
              <button type="button" class="button py-3" onclick="confirmJalan()">Mulai Jalan</button>
            </div>
            <div class="m-2">
              <button type="button" class="button-outline py-3" onclick="confirmDelete()">Hapus Tumpangan</button>
            </div>
          </div>
        {% endif %}
      </div>      
    </div>
    
    <script>
    function endTumpangan() {
      var tumpanganId = $("#tumpanganId").val();
      confirmTumpangan(tumpanganId);
    }

    function updatePenumpangButton(status_tumpangan, pengajuan, pengguna) {
      var buttonArea = document.getElementById(`status-${pengajuan.id}`)
      var buttonText = ""

      
      if (status_tumpangan === 'OP') {
        if (pengajuan.status_pengajuan.toUpperCase() === 'MENGAJUKAN') {
          buttonText = `<button type="button" class="button py-3" onclick="updateTumpangan('${pengajuan.id}', 'DITERIMA')">Terima</button>`
        } else  {
          buttonText = `<button type="button" class="button-acc py-3" disabled>Diterima</button>`
        }
      } else {
        if (pengguna.no_wa) {
          buttonText += `<a href="https://wa.me/+62${pengguna.no_wa}" target="_blank" class="button py-3 m-1"><img class="icon" src="{% static 'image/wa.png' %}" /></a>`
        } if (pengguna.id_line) {
          buttonText += `<a href="https://line.me/R/ti/p/~${pengguna.id_line}" target="_blank" class="button-outline py-3 m-1"><img class="icon" src="{% static 'image/line.png' %}" /></a>`
        }
        buttonText += `
        <a type="button" href="https://nebeng-dong.vercel.app/report/{{id}}" class="button-outline py-3 m-1"><img class="icon" src="{% static 'image/report.png' %}" /> Report</a>
        `
      }
      buttonArea.innerHTML = buttonText
    }

    var counter = 0
    function addCounter() {
      counter++
      $("#counter-penumpang").html(`${counter} penumpang diterima`)
    }
  
    function confirmTumpangan(tumpanganId) {
      $.ajax({
        type: "POST",
        url: `/buka-tumpangan/confirm_tumpangan/${tumpanganId}/`,
        dataType: "json",
        success: function(data) {
          updateButtonAfterConfirm()
          showAlert("SUCCESS", data.message,'OK', '', '', '')
        },
        error: function(error) {
          showAlert("FAILED", "gagal memperbarui status",'OK', '', '', '')
        }
      });
    }

    function updateStatusHTML(pengajuan_id, status) {
      item_penumpang = document.getElementById(`status-${pengajuan_id}`)
      if (status === 'DITERIMA') {
        item_penumpang.innerHTML = '<button class="button-acc py-3" disabled>Diterima</button>'
      } else {
        item_penumpang.innerHTML = '<button class="button-acc py-3" disabled>Ditolak</button>'
      }
    }

    function addCardPengajuan(status_tumpangan, pengajuan, pengguna) {
        if (pengajuan.status_pengajuan === 'DITOLAK') {
          return;
        }

        $(".penumpang").append(`
          <div class="box row rows-cols-1 row-cols-md-3 d-flex justify-content-between align-items-center mr-5 my-4 p-4" id="pengajuan-${pengajuan.id}">
            <div class="mr-5">
              <div class="text-nowrap"><b>${pengguna.nama}</b></div>
              <div class="text-nowrap">Fakultas ${pengguna.fakultas}</div>
            </div>
            <div class='d-flex justify-content-between my-2' id="status-${pengajuan.id}">
            </div>
          </div>
        `)

        updatePenumpangButton(status_tumpangan, pengajuan, pengguna)
      }

    function confirmJalan() {
      if (counter.toString() === '0') {
        showAlert('FAILED', 'Penumpangmu masih kosong',
                  'Back', '','', '')
        return;
      }
      showAlert('SUCCESS', 'Apakah kamu yakin ingin memulai tumpangan ini? *Penumpang yang belum diterima akan otomatis ditolak',
      'Ya, Mulai Jalan', () => closeOffer('{{id}}'),
      'Batal', ''
      )

    }

    function confirmDelete() {
      showAlert('FAILED', 'Apakah kamu yakin ingin menghapus tumpangan ini?',
      'Ya, Hapus', () => deleteTumpangan('{{id}}'),
      'Batal', ''
      )
    }

    var kapasitas = '{{kapasitas}}'
    var updateTumpangan = function(pengajuan_id, status) {
      if (counter.toString() === kapasitas) {
        showAlert('FAILED', 'Kapasitas sudah penuh',
                  'Mulai Jalan', () => closeOffer('{{id}}'),
                  'Back', '')
        return;
      }
      $.ajax({
            type: "PUT",
            headers: { "X-CSRFToken": document.getElementsByName("csrfmiddlewaretoken")[0].value },
            url: `/buka-tumpangan/update/${pengajuan_id}/${status}/`,
            encode: true,
          }).done(function (data) {
            console.log(data)
            updateStatusHTML(pengajuan_id, status)
            addCounter()
          })
    }

    function updateButtons() {
      divOT = document.getElementById('buttonOT')
      divOT.innerHTML = `
      <div class="d-flex justify-content-center gap-2">
        <div class="m-2">
          <form method="post" id="confirmForm">
            <input type="hidden" id="tumpanganId" value="{{id}}">
            {% csrf_token %}
            <button type="button" class="m-2 button mr-2 py-3" id="confirmButton" onclick="endTumpangan()">Tumpangan Selesai</button>
          </form>
        </div>
        <div class="m-2">
          <!-- Panic Button -->
          <a type="button" href="tel:+6281291203330" class="m-2 button-outline mr-2 py-3" id="panicButton">
            <img class="icon" src="{% static 'image/panic.png' %}" />Panic Button
          </a>
        </div>
      </div>
      `
      document.getElementById('buttonOP').innerHTML = ''
    }

    function updateButtonAfterConfirm() {
      document.getElementById('buttonOT').innerHTML = ''
    }

    function getPengajuanTerbaru(status_tumpangan) {
        $(".penumpang").html("");
        $.getJSON( '/buka-tumpangan/get-pengajuan/{{id}}', function( data ) {
            counter = data.jml_diterima
            $("#counter-penumpang").html(`${counter} penumpang diterima`)
            var penumpang = data.data
            penumpang.forEach(element => {
              addCardPengajuan(status_tumpangan, element.pengajuan, element.pengguna);
            });
        });
      }

    function closeOffer(tumpanganId) {
      $.ajax({
        type: "PUT",
        headers: { "X-CSRFToken": document.getElementsByName("csrfmiddlewaretoken")[0].value },
        url: `/buka-tumpangan/close-offer/${tumpanganId}/`,
        dataType: "json"
      }).done(function (data) {
        getPengajuanTerbaru("OT");
        updateButtons();
        showAlert('SUCCESS', 'Berhasil memulai tumpangan! Yuk, hubungi penumpangmu',
                  'OK', '', '', '')
        });
    }

    var deleteTumpangan = function(pk) {
      $.ajax({
            type: "DELETE",
            headers: { "X-CSRFToken": document.getElementsByName("csrfmiddlewaretoken")[0].value },
            url: "{% url 'buka_tumpangan:delete_tumpangan' 1 %}".replace(1, pk),
            encode: true,
          }).done(function (data) {
            showAlert('SUCCESS', 'Berhasil menghapus tumpangan!',
                    'Back to Home', () => {window.location.href = "/"}, 
                    '', '')
          })
    }

    getPengajuanTerbaru("{{status}}");
    </script>
    <script type="text/javascript" src="{% static 'js/manage_tumpangan.js' %}"></script>

 {% endblock content %}