NebengDong/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/auth/", include("authentication.urls")),
    path('profile/', include('user_profile.urls')),
    path('history/', include('history.urls')),
    path('report/', include('report_pengguna.urls')),
    path('buka-tumpangan/', include('buka_tumpangan.urls')),
    path('cari-tumpangan/', include('cari_tumpangan.urls')),
    path('report-list/', include('report_list.urls')),
    path('', include("home.urls"))
]

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', index, name='home'),
]

user_profile/urls.py
from django.urls import path
from .views import *

app_name = 'user_profile'

urlpatterns = [
    path('profile-pengguna/', get_profile_pengguna, name='get_profile_pengguna'),
    path('update-pengguna/', update_profile_pengguna, name='update_profile_pengguna'),
    path('profile-tim/', get_profile_tim, name='get_profile_tim'),
    path('update-password/', update_password_tim, name='update_password_tim'),
]

user_profile/models.py
from django.db import models

# Create your models here.

user_profile/views.py
from nebengdongapp.models import Pengguna
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist

@login_required(login_url='/api/auth/home')
def get_profile_tim(request):
    user = request.user
    try:
        pengguna = Pengguna.objects.get(user_id=user.id)
        return redirect('user_profile:get_profile_pengguna')
    except ObjectDoesNotExist:
        profile_data = {
            'role': "Tim Layanan Pengguna",
            'username': user.username,
            'first_name': user.first_name
        }
        
        return render(request, 'profile_tim.html', profile_data)
    
@login_required(login_url='/api/auth/home')
def get_profile_pengguna(request):
    user = request.user
    try:
        pengguna = Pengguna.objects.get(user_id=user.id)
        status_tumpangan = ""
        
        if pengguna.is_on_tumpangan:
            status_tumpangan = "Aktif"
        else:
            status_tumpangan = "Tidak aktif"

        profile_data = {
            'role': "Pengguna",
            'nama': pengguna.nama,
            'email': pengguna.email,
            'fakultas': pengguna.fakultas,
            'no_wa' : pengguna.no_wa,
            'id_line': pengguna.id_line,
            'no_kendaraan' : pengguna.no_kendaraan,
            'Status_tumpangan': status_tumpangan
        }

        return render(request, 'profile_pengguna.html', {'profile_data': profile_data})
    except ObjectDoesNotExist:
        return redirect('/profile/profile-tim')

@csrf_exempt
@login_required(login_url='/api/auth/home')
def update_password_tim(request):
    try:
        user = request.user
        if request.method == 'POST':
            # Get the current password and new password from the request
            current_password = request.POST.get('current_password')
            new_password = request.POST.get('new_password')
            password_confirm = request.POST.get('confirm_password')
            
            # Check if the new password is empty
            if not new_password:
                return JsonResponse({
                    "status": False,
                    "message": "Password baru tidak boleh kosong.",
                }, status=400)

            # Check if the current password is correct
            if not check_password(current_password, user.password):
                return JsonResponse({
                    "status": False,
                    "message": "Password saat ini salah.",
                }, status=400)
                
            # check if the new password match the password confirmation
            elif new_password != password_confirm:
                print(new_password)
                print(password_confirm)
                return JsonResponse({
                    "status": False,
                    "message": "Password baru yang dimasukkan tidak sama.",
                }, status=400)
        
            # Update the password securely
            user.set_password(new_password)
            user.save()

            # Update the session to prevent the user from being logged out
            update_session_auth_hash(request, user)

            return JsonResponse({
                "status": True,
                "message": "Password baru berhasil disimpan!",
            }, status=200)

        else:
            return JsonResponse({
                "status": False,
                "message": "Invalid request method. Use POST.",
            }, status=405)

    except Exception as e:
        print(e)
        return JsonResponse({
            "status": False,
            "message": "Operation Failed."
        }, status=500)

@csrf_exempt   
@login_required(login_url='/api/auth/home')
def update_profile_pengguna(request):
    # periksa jika rolenya pengguna
    try:
        pengguna = Pengguna.objects.get(user_id=request.user.id)
        if request.method == 'POST':
            new_no_wa = request.POST.get('new_no_wa', '')
            new_id_line = request.POST.get('new_id_line', '')
            new_no_kendaraan = request.POST.get('new_no_kendaraan', '')
            
            # Check if any of the required fields is missing
            if not new_no_wa and not new_id_line:
                return JsonResponse(
                    {
                        "error": "Gagal memperbarui informasi. Mohon beri salah satu kontak."
                    },
                    status=400  # Bad Request
                )
                
            if (new_no_wa and not new_no_wa.isdigit()) or (new_no_wa and int(new_no_wa) <= 0):
                return JsonResponse(
                    {
                        "error": "Gagal memperbarui informasi. No WA yang dimasukkan tidak valid."
                    },
                    status=400  # Bad Request
                )

            # Update if valid
            pengguna.no_wa = new_no_wa
            pengguna.id_line = new_id_line
            pengguna.no_kendaraan = new_no_kendaraan

            pengguna.save()
            return JsonResponse(
                {
                    "message": f"Berhasil memperbarui informasi!"
                }, 
                status=200
            )

    except ObjectDoesNotExist:
        # maka merupakan tim layanan pelanggan
        return redirect('/profile/profile-tim')

user_profile/templates/profile_pengguna.html
{% extends 'base.html' %}
{% load static %}

 {% block meta %}
  <title>{{ profile_data.nama }}</title>
  <style>

    body {
    font-family: 'Poppins';
    }

    .container {
        display: flex;
        width: 100%;
        padding: 32px 80px;
        flex-direction: column;
        align-items: flex-start;
        row-gap: 8px;
    }

    label {
        display: block;
        margin-bottom: 5px;
    }

    input {
        width: 100%;
        padding: 8px 8px 8px 16px;
        box-sizing: border-box;
    }

    .btn-group {
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 8px;
        align-self: stretch;
    }

    .row {
        padding-bottom:8px
    }

    .col-md-6 {
        padding-bottom:8px
    }

    .badge {
        border-radius: 40px;
        background: linear-gradient(182deg, #FFCA0D 2.05%, #DCAB00 114.14%);
        padding: 8px;
        color: var(--120-dfa, #120DFA);
        font-size: 16px;
        font-style: normal;
        font-weight: 700;
        line-height: normal;
    }

    .info-group {
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
        align-content: flex-start;
        align-self: stretch;
        flex-wrap: wrap;
        padding: 8px 0px 20px 0px;
    }
</style>
 {% endblock meta %}
 {% block content %}
    <div class="container">
        <h2><b><span style="color: #FFCA0D;">Halo,</span> <span style="color: #120DFA;">{{profile_data.nama}}!</span></b></h2>
        <span class="badge">{{ profile_data.role }}</span>

        <form id="updateForm">
            {% csrf_token %}
            <div class="info-group  w-100">
                <div class="row w-100">
                    <div class="col-md-6">
                            <label for="name"><b>Nama</b></label>
                            <div class="input-group">
                            <input type="text" class="form-control w-100" id="name" aria-describedby="basic-addon3" disabled value="{{ profile_data.nama }}">
                            </div>
                    </div>
                    <div class="col-md-6">
                            <label for="status_tump"><b>Status Tumpangan</b></label>
                            <div class="input-group">
                            <input type="text" class="form-control w-100" id="status_tump" aria-describedby="basic-addon3" disabled value="{{ profile_data.Status_tumpangan }}">
                            </div>
                    </div>
                </div>
                <div class="row w-100">
                    <div class="col-md-6">
                        <label for="basic-url"><b>Fakultas</b></label>
                        <div class="input-group">
                        <input type="text" class="form-control  w-100" id="basic-url" aria-describedby="basic-addon3" disabled value="{{ profile_data.fakultas}}">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="basic-url"><b>No WhatsApp</b></label>
                        <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" style="background: #120DFA; color:white" id="basic-addon3">+62</span>
                        </div>
                        <input type="number" class="form-control" style="border-color: #120DFA; border-width: 2px" aria-describedby="basic-addon3" id="new_no_wa" name="new_no_wa" pattern="[0-9]*" value="{{ profile_data.no_wa }}">
                        </div>
                    </div>
                </div>
                <div class="row w-100">
                    <div class="col-md-6">
                        <label for="new_id_line"><b>ID LINE</b></label>
                        <div class="input-group">
                            <input type="text" aria-describedby="basic-addon3" style="border-color: #120DFA; border-width: 2px" class="form-control" id="new_id_line" name="new_id_line" value="{{ profile_data.id_line }}">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="new_no_kendaraan"><b>No Kendaraan</b></label>
                    <div class="input-group">
                    <input type="text" aria-describedby="basic-addon3" style="border-color: #120DFA; border-width: 2px" class="form-control" id="new_no_kendaraan" name="new_no_kendaraan" value="{{ profile_data.no_kendaraan }}">
                    </div>
                    </div>
                </div>
            </div>
        
            <div class="btn-group">
                <button type="submit" class="button" id="saveButton" onclick="submitForm(event)" >Save</button>
                <button type="button" class="cancel-button button-outline" onclick="window.location.href='{% url 'user_profile:get_profile_pengguna' %}'">Cancel</button>
            </div>
        </form>
    </div>

    <script>        
        function submitForm(event) {
            event.preventDefault();

            var formData = $("#updateForm").serialize();
    
            $.ajax({
                type: "POST",
                url: "{% url 'user_profile:update_profile_pengguna' %}",
                data: formData,
                success: function(response) {
                    showAlert('SUCCESS', response.message,
                    'Close', '', 
                    '', '')
                },
                error: function(error) {
                    showAlert('FAILED', error.responseJSON.error,
                    'Close', '', 
                    '', '')
                }
            });
        }
    </script>
    

 {% endblock content %}  

user_profile/templates/profile_tim.html
{% extends 'base.html' %}
{% load static %}

 {% block meta %}
  <title>{{ profile_data.username }}</title>
 <style>

    body {
        font-family: 'Poppins';
    }
    
    .container {
        display: flex;
        width: 100%;
        padding: 32px 80px;
        flex-direction: column;
        align-items: flex-start;
        row-gap: 8px;
    }

    .row {
        padding-bottom:8px
    }

    .col-md-6 {
        padding-bottom:8px
    }

    label {
        display: block;
        margin-bottom: 5px;
    }

    input {
        width: 100%;
        padding: 8px;
        box-sizing: border-box;
    }

    .badge {
        border-radius: 40px;
        background: linear-gradient(182deg, #FFCA0D 2.05%, #DCAB00 114.14%);
        padding: 8px;
        color: var(--120-dfa, #120DFA);
        font-size: 16px;
        font-style: normal;
        font-weight: 700;
        line-height: normal;
    }

    .info-group {
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
        align-content: flex-start;
        align-self: stretch;
        flex-wrap: wrap;
        padding: 8px 0px 20px 0px;
    }

    .btn-group {
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 8px;
        align-self: stretch;
    }
</style>
{% endblock meta %}
{% block content %}
 <div class="container">
    <h2><b><span style="color: #FFCA0D;">Halo,</span> <span style="color: #120DFA;">{{username}}!</span></b></h2>
    <span class="badge">{{ role }}</span>

    <form id="updatePasswordForm">
        {% csrf_token %}
        <div class="info-group w-100">
            <div class="row w-100">
                <div class="col-md-6">
                    <label for="name"><b>Nama</b></label>
                    <div class="input-group">
                    <input type="text" class="form-control w-100" id="name" aria-describedby="basic-addon3" disabled value="{{ first_name }}">
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="name"><b>Username</b></label>
                    <div class="input-group">
                    <input type="text" class="form-control w-100" id="name" aria-describedby="basic-addon3" disabled value="{{ username }}">
                    </div>
                </div>
            </div>
            <div class="row w-100">
                <div class="col-md-6">
                    <label for="current_password"><b>Current Password:</b></label>
                    <input class="form-control" style="border-color: #120DFA; border-width: 2px" aria-describedby="basic-addon3" type="password" name="current_password" required>               
                 </div>
            </div>
            <div class="row w-100">
                <div class="col-md-6">
                    <label for="new_password"><b>New Password:</b></label>
                    <input class="form-control" style="border-color: #120DFA; border-width: 2px" aria-describedby="basic-addon3" type="password" name="new_password" required>
                </div>
                <div class="col-md-6">
                    <label for="confirm_password"><b>Confirm Password:</b></label>
                    <input class="form-control" style="border-color: #120DFA; border-width: 2px" aria-describedby="basic-addon3" type="password" name="confirm_password" required>
                </div>
            </div>
        </div>

        <div class="btn-group">
            <button type="button" class="button" onclick="updatePass()">Save</button>
            <button type="button" class="cancel-button button-outline" onclick="window.location.href='{% url 'user_profile:get_profile_tim' %}'">Cancel</button>
        </div>
    </form>
    
 </div>

<div class="modal" id="successModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Success!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <center>
                <img src="{% static 'image/success_img.png' %}" />
                <p style="padding:10px">Password baru berhasil disimpan!</p>
                </center>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="failedModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="successModalContent">
            <div class="modal-header">
                <h5 class="modal-title">Failed!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="successModalBody">
            </div>
            <!-- Modal content will be dynamically set by JavaScript -->
        </div>
    </div>
</div>

<script>
     function updatePass() {
         var form = document.getElementById("updatePasswordForm");
         var formData = new FormData(form);
 
         fetch('/profile/update-password/', {
             method: 'POST',
             body: formData,
         })
         .then(response => response.json())
         .then(data => {
             if (data.status) {
                showSuccessPopup();
                form.reset();
             } else {
                showFailedPopup(data.message);
             }
         })
         .catch(error => console.error('Error:', error));
     }

     
    function showSuccessPopup() {
        // Use Bootstrap modal to show a pop-up
        var myModal = new bootstrap.Modal(document.getElementById('successModal'));
        myModal.show();
    }

    function showFailedPopup(message) {
        // Use Bootstrap modal to show a pop-up
        var myModal = new bootstrap.Modal(document.getElementById('failedModal'));

           // Set dynamic content in the modal
      document.getElementById('successModalBody').innerHTML = `
        <div class="modal-body">
            <center>
            <img src="{% static 'image/failed_img.png' %}" />
            <p style="margin:24px">${message}</p>
            </center>
        </div>
    `;

        myModal.show();
    }
 </script>
{% endblock content %}  