NebengDong/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/auth/", include("authentication.urls")),
    path('profile/', include('user_profile.urls')),
    path('history/', include('history.urls')),
    path('report/', include('report_pengguna.urls')),
    path('buka-tumpangan/', include('buka_tumpangan.urls')),
    path('cari-tumpangan/', include('cari_tumpangan.urls')),
    path('report-list/', include('report_list.urls')),
    path('', include("home.urls"))
]

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', index, name='home'),
]

templates/alert.html
{% load static %}

<style>
    .modal-content {
        border-radius: 26px;
        max-width: fit-content;
        background: #FFF;
        box-shadow: -1px 1px 4px 0px rgba(0, 0, 0, 0.25), 7px 7px 4px 0px rgba(0, 0, 0, 0.25);       
    }

    .modal-footer {
        border-top: none;
    }
</style>

<!-- custom modal dialog -->
<div class="modal" tabindex="-1" role="dialog" id="customAlertModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content p-4">
            <div class="modal-body items-center mx-auto" id="alert-body"> 
            </div>
            <div class="d-flex justify-content-center border-top-0 modal-footer">
                <button type="button" class="button mx-2" data-dismiss="modal" id="prim-btn"></button>
                <button type="button" class="button-outline mx-2" data-dismiss="modal" id="second-btn"></button>
            </div>
        </div>
    </div>
</div>

<script>
function showAlert(type, msg,    // type: either SUCCESS or FAILED
                    txtButtonPrimary, onclickPrim, 
                    txtButtonSecondary, onclickScnd) {

    var alertImg = ''                    
    if (type === 'SUCCESS') {
        alertImg = `<img class='mx-auto my-3' src="{% static 'image/success_img.png' %}" />`
    } else {
        alertImg = `<img class='mx-auto my-3' src="{% static 'image/failed_img.png' %}" />`
    }
    document.getElementById('alert-body').innerHTML = `
        <div class='my-2'>${msg}</div>        
        <div class='px-auto d-flex justify-content-center'>${alertImg}</div>
    `;
    if (txtButtonPrimary !== "") {
        var primBtn = document.getElementById('prim-btn');
        primBtn.innerHTML = txtButtonPrimary;
        primBtn.onclick = onclickPrim;
    } else {
        $("#prim-btn").hide()
    }

    if (txtButtonSecondary !== "") {
        var secondBtn = document.getElementById('second-btn');
        secondBtn.innerHTML = txtButtonSecondary;
        secondBtn.onclick = onclickScnd;
    } else {
        $("#second-btn").hide()
    }

    $('#customAlertModal').modal('show');
}
</script>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
  <!-- Bootstrap JS and dependencies -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="icon" href="{% static 'image/logo_icon.png' %}">
  <!-- jQuery for AJAX -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  
  <!-- Bootstrap JS and dependencies -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% include 'nav.html' %}
  <div class="content">
    {% block content %}
    {% endblock content %}    
    {% include 'alert.html' %}
  </div>

  <footer class="footer custom-footer" style="font-family: 'Poppins', sans-serif;">
    <img src="{% static 'image/logo_footer.png' %}" />
   <div class="developer"> <h4><b>Developers</b></h4>
    <p>Divany Harryndira</p>
    <p>Ghayda Rafa</p>
    <p>Naila Shafirni</p>
    <p>Rania Maharani</p>
    <p>Syadza Nayla</p></div>
  </footer>
</body>

</html>

templates/nav.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
      <a class="navbar-brand" href="{% url 'home:home' %}">
        <img src="{% static 'image/logo_nav.png' %}" />
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated and not user.is_superuser %}
          <li class="nav-item active">
            <a class="nav-link" href="/cari-tumpangan/">Cari Tumpangan <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href='#' onclick="clickBukaTumpangan()">Buka Tumpangan <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/history/">History <span class="sr-only">(current)</span></a>
          </li>
          {% elif user.is_authenticated and user.is_superuser %}
          <li class="nav-item active">
            <a class="nav-link" href="/report-list/">Laporan <span class="sr-only">(current)</span></a>
          </li>
          {% endif %}
        </ul>
          {% if user.is_authenticated %}
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <a class="nav-link" href='/profile/profile-pengguna/'>Profile</a>
            </li>
          </ul>
          <div>
            <a href="/api/auth/logout/">
              <button class="button">Logout</button>
            </a>
          </div>
          {% elif request.path != '/api/auth/home/'  %}
          <div>
            <a href="/api/auth/home/">
              <button class="button">Login</button>
            </a>
          </div>
          {% endif %}
      </div>
    </nav>
  </header>
  <script>
    var clickBukaTumpangan = function() {
      $.ajax({
          type: "GET",
          url: "/buka-tumpangan/check-no-kendaraan/",
        }).done(function (data) {
            msg = data.message
            console.log(msg)
            if (msg !== 'success') {
                showAlert('FAILED', msg, 
                        'Edit Profile', () => {window.location.href='/profile/profile-pengguna/'}, 
                        'Back', '')
                return false;
            } else {
                window.location.href='/buka-tumpangan/new/'
            }
        })
    } 
  </script>